modLoader="javafml" 
loaderVersion="${loader_version_range}"
license="${mod_license}"

[[mods]] 
modId="${lib_mod_id}" 
version="${lib_mod_version}"
license="${lib_mod_license}"
displayName="${lib_mod_name}" 
authors="${lib_mod_authors}" 
description='''${lib_mod_description}'''

[[mods]] 
modId="${test_mod_id}" 
version="${test_mod_version}"
license="${test_mod_license}"
displayName="${test_mod_name}" 
authors="${test_mod_authors}" 
description='''${test_mod_description}'''

[[dependencies."${lib_mod_id}"]] 
   modId="forge" 
   mandatory=true 
   versionRange="${forge_version_range}" 
   ordering="NONE"
   side="BOTH"
[[dependencies."${lib_mod_id}"]]
   modId="minecraft"
   mandatory=true
   versionRange="${minecraft_version_range}"
   ordering="NONE"
   side="BOTH"

[[dependencies."${lib_mod_id}"]]
   modId="youkaishomecoming"
   mandatory=true
   versionRange="${youkaishomecoming_version_range}"
   ordering="NONE"
   side="BOTH"

[[dependencies."${test_mod_id}"]]
   modId="${lib_mod_id}"
   mandatory=true
   versionRange="ANY"
   ordering="NONE"
   side="BOTH"